name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp: [['27.1', '3.22.1']]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Setup Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp[0] }}
          rebar3-version: ${{ matrix.otp[1] }}
      - run: |
          make
          make fmt-check
          make xref
          make dialyzer
          make test-env
          make ct
          make cover
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
